# Generated by Django 3.1.7 on 2021-05-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='upload',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
