# Generated by Django 3.1.7 on 2021-05-30 00:42

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210529_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='upload',
            field=models.ImageField(upload_to=posts.models.user_directory_path),
        ),
    ]
