# Generated by Django 3.1.7 on 2021-05-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210529_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
