# Generated by Django 3.1.7 on 2021-06-02 23:38

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.user_category_path),
        ),
    ]
