# Generated by Django 3.1.7 on 2021-06-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_nsfw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='NSFW',
            new_name='NSFWs',
        ),
    ]
